### ISSUE TITLE
database

### ISSUE THREAD

**Issue by NFebri** [erpeel-a/Sistem-Pengaduan-Sekolah-SMKN2Karanganyar#1]
@Zainal21 schema database

**Comment by Zainal21** [comment]
> @Zainal21 schema database

proses..

**Comment by Zainal21** [comment]
> @Zainal21 schema database

Rancangan e uwes.... pindah branch sek nang branch zain-develop... schema database nk ijek rancu/kurang normalisasi-nen gpp...

**Comment by NFebri** [comment]
Oke
